repos:
  - repo: local
    hooks:
      - id: generate-docs
        name: Generating Environment Docs
        entry: python scripts/generate_env_docs.py
        language: system
        types: [python]
        pass_filenames: false
